### ISSUE TITLE
TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by cmdrrobin** [antonlegoo/gitbook-plugin-changelog#1]
When loading changelog plugin into my gitbook I get the following error message:

```
ive reload server started on port: 35729
Press CTRL+C to quit ...

info: 10 plugins are installed
info: loading plugin "bootstrap-callout"... OK
info: loading plugin "code"... OK
info: loading plugin "changelog"... OK
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 8 pages
info: found 2 asset files

TypeError: Cannot read property 'files' of undefined
```

I use the following Gitbook version.
```
CLI version: 2.3.2
GitBook version: 3.2.3
```

**Comment by beeman** [comment]
Getting the same error, same versions of CLI and GitBook.

**Comment by antonlegoo** [comment]
@rgruyters @beeman I've released an update that should address this. Please try upgrading to version `1.0.1` and see if it resolves the issue.

For prosperity, what was happening is a commit in your history was not producing any changes. For example, if you had only one single "initial" commit then no diff change could be produced since it had no others commits to compare to. Not sure if this was your case, but it was how I reproduced the error. I've solved the issue by filtering out these "null" commits.

**Comment by beeman** [comment]
Thanks a lot @antonlegoo, that seems to have fixed it!
